#!/usr/bin/env bash

#SBATCH --job-name=deploy
#SBATCH --account=use300
#SBATCH --clusters=expanse
#SBATCH --partition=ind-gpu-shared
#SBATCH --qos=gpu-unlim
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --gpus=1
#SBATCH --time=00:30:00
#SBATCH --output=%x.o%j.%N

declare -xir UNIX_TIME="$(date +'%s')"
declare -xr LOCAL_TIME="$(date +'%Y%m%dT%H%M%S%z')"

declare -xr JOB_SCRIPT="$(scontrol show job ${SLURM_JOB_ID} | awk -F= '/Command=/{print $2}')"
declare -xr JOB_SCRIPT_MD5="$(md5sum ${JOB_SCRIPT} | awk '{print $1}')"
declare -xr JOB_SCRIPT_SHA256="$(sha256sum ${JOB_SCRIPT} | awk '{print $1}')"
declare -xr JOB_SCRIPT_NUMBER_OF_LINES="$(wc -l ${JOB_SCRIPT} | awk '{print $1}')"

declare -xr SCHEDULER_NAME='slurm'
declare -xr SCHEDULER_MAJOR='23'
declare -xr SCHEDULER_MINOR='02'
declare -xr SCHEDULER_REVISION='7'
declare -xr SCHEDULER_VERSION="${SCHEDULER_MAJOR}.${SCHEDULER_MINOR}.${SCHEDULER_REVISION}"
declare -xr SCHEDULER_MODULE="${SCHEDULER_NAME}/${SLURM_CLUSTER_NAME}/${SCHEDULER_VERSION}"

declare -xr SPACK_MAJOR='0'
declare -xr SPACK_MINOR='21'
declare -xr SPACK_REVISION='2'
declare -xr SPACK_VERSION="${SPACK_MAJOR}.${SPACK_MINOR}.${SPACK_REVISION}"
declare -xr SPACK_INSTANCE_NAME='gpu'
declare -xr SPACK_INSTANCE_VERSION='dev'
declare -xr SPACK_INSTANCE_DIR='/home/mkandes/software/spack/repos/sdsc/gpu'

echo "${UNIX_TIME} ${LOCAL_TIME} ${SLURM_JOB_ID} ${JOB_SCRIPT_MD5} ${JOB_SCRIPT_SHA256} ${JOB_SCRIPT_NUMBER_OF_LINES} ${JOB_SCRIPT}"
cat  "${JOB_SCRIPT}"

module purge
module load "${SCHEDULER_MODULE}"
module list
. "${SPACK_INSTANCE_DIR}/share/spack/setup-env.sh"
printenv

spack config get compilers  
spack config get config  
spack config get mirrors
spack config get modules
spack config get packages
spack config get repos
spack config get upstreams

cp -p yamls/compilers.yaml "${SPACK_INSTANCE_DIR}/etc/spack/compilers.yaml"
cp -p yamls/modules.yaml "${SPACK_INSTANCE_DIR}/etc/spack/modules.yaml"
cp -p yamls/packages.yaml "${SPACK_INSTANCE_DIR}/etc/spack/packages.yaml"

cd "${SLURM_SUBMIT_DIR}/specs"
BZIP2_JOB_ID="$(sbatch 'bzip2@1.0.8.sh' | grep -o '[[:digit:]]*')"
  CURL_JOB_ID="$(sbatch --dependency="afterok:${BZIP2_JOB_ID}" 'curl@8.4.0.sh' | grep -o '[[:digit:]]*')"
    CMAKE_JOB_ID="$(sbatch --dependency="afterok:${CURL_JOB_ID}" 'cmake@3.31.2.sh' | grep -o '[[:digit:]]*')"
      INTEL_ONEAPI_JOB_ID="$(sbatch --dependency="afterok:${CMAKE_JOB_ID}" 'intel-oneapi-compilers@2023.2.4.sh' | grep -o '[[:digit:]]*')"
    GCC_JOB_ID="$(sbatch --dependency="afterok:${CURL_JOB_ID}" 'gcc@11.5.0.sh' | grep -o '[[:digit:]]*')"
      GCC_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'gcc@13.3.0.sh' | grep -o '[[:digit:]]*')"
        SQLITE_JOB_ID="$(sbatch --dependency="afterok:${CMAKE_JOB_ID}:${GCC_JOB_ID}" 'sqlite@3.43.2.sh' | grep -o '[[:digit:]]*')"
          ARIA2_JOB_ID="$(sbatch --dependency="afterok:${SQLITE_JOB_ID}" 'aria2@1.37.0.sh' | grep -o '[[:digit:]]*')"
          GDB_JOB_ID="$(sbatch --dependency="afterok:${SQLITE_JOB_ID}" 'gdb@14.2.sh' | grep -o '[[:digit:]]*')"
            MERCURIAL_JOB_ID="$(sbatch --dependency="afterok:${GDB_JOB_ID}" 'mercurial@6.8.1.sh' | grep -o '[[:digit:]]*')"
    PERL_JOB_ID="$(sbatch --dependency="afterok:${CURL_JOB_ID}" 'perl@5.38.2.sh' | grep -o '[[:digit:]]*')"
      ENTREZDIRECT_JOB_ID="$(sbatch --dependency="afterok:${PERL_JOB_ID}" 'entrezdirect@22.6.20240924.sh' | grep -o '[[:digit:]]*')"
      GIT_JOB_ID="$(sbatch --dependency="afterok:${PERL_JOB_ID}" 'git@2.45.2.sh' | grep -o '[[:digit:]]*')"
        GO_JOB_ID="$(sbatch --dependency="afterok:${GIT_JOB_ID}" 'go@1.23.1.sh' | grep -o '[[:digit:]]*')"
          GITLFS_JOB_ID="$(sbatch --dependency="afterok:${GO_JOB_ID}" 'git-lfs@3.5.1.sh' | grep -o '[[:digit:]]*')"
          GH_JOB_ID="$(sbatch --dependency="afterok:${GO_JOB_ID}" 'gh@2.57.0.sh' | grep -o '[[:digit:]]*')"
          RCLONE_JOB_ID="$(sbatch --dependency="afterok:${GO_JOB_ID}" 'rclone@1.68.1.sh' | grep -o '[[:digit:]]*')"
      PARALLEL_JOB_ID="$(sbatch --dependency="afterok:${PERL_JOB_ID}" 'parallel@20240922.sh' | grep -o '[[:digit:]]*')"
      SUBVERSION_JOB_ID="$(sbatch --dependency="afterok:${GDB_JOB_ID}:${PERL_JOB_ID}:${SQLITE_JOB_ID}" 'subversion@1.14.3.sh' | grep -o '[[:digit:]]*')"
    PIGZ_JOB_ID="$(sbatch --dependency="afterok:${CURL_JOB_ID}" 'pigz@2.8.sh' | grep -o '[[:digit:]]*')"
      TAR_JOB_ID="$(sbatch --dependency="afterok:${PIGZ_JOB_ID}" 'tar@1.34.sh' | grep -o '[[:digit:]]*')"
  NVHPC_JOB_ID="$(sbatch --dependency="afterok:${BZIP2_JOB_ID}" 'nvhpc@24.11.sh' | grep -o '[[:digit:]]*')"
  OPENJDK_JOB_ID="$(sbatch --dependency="afterok:${BZIP2_JOB_ID}" 'openjdk@11.0.24_8.sh' | grep -o '[[:digit:]]*')"
  SRATOOLKIT_JOB_ID="$(sbatch --dependency="afterok:${BZIP2_JOB_ID}" 'sratoolkit@3.1.1.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@11.5.0"
CUDA_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'cuda@11.8.0.sh' | grep -o '[[:digit:]]*')"
  CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  CUDNN_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cudnn@9.6.0.74-11.sh' | grep -o '[[:digit:]]*')"
  CUTENSOR_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cutensor@2.0.2.5.sh' | grep -o '[[:digit:]]*')"
  NCCL_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'nccl@2.18.5-1.sh' | grep -o '[[:digit:]]*')"
EIGEN_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'eigen@3.4.0.sh' | grep -o '[[:digit:]]*')"
  FFTW_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
    FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
    NAMD2_JOB_ID="$(sbatch --dependency="afterok:${CHARMPP_JOB_ID}:${FFTW_JOB_ID}" 'namd@2.14.sh' | grep -o '[[:digit:]]*')"
  GSL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'gsl@2.8.sh' | grep -o '[[:digit:]]*')"
  LIBXC_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libxc@7.0.0.sh' | grep -o '[[:digit:]]*')"
  LIBBEAGLE_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libbeagle@3.1.2.sh' | grep -o '[[:digit:]]*')"
    BEAST2_JOB_ID="$(sbatch --dependency="afterok:${LIBBEAGLE_JOB_ID}" 'beast2@2.7.7.sh' | grep -o '[[:digit:]]*')"
  HDF5_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
    NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
      NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
      NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
  METIS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'metis@5.1.0.sh' | grep -o '[[:digit:]]*')"
  MVAPICH2_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'mvapich2@2.3.7-2.sh' | grep -o '[[:digit:]]*')"
  NETLIB_LAPACK_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'netlib-lapack@3.12.0.sh' | grep -o '[[:digit:]]*')"
  OPENBLAS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'openblas@0.3.28.sh' | grep -o '[[:digit:]]*')"
    MAGMA_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${OPENBLAS_JOB_ID}" 'magma@2.9.0.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-omp.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64-omp.sh' | grep -o '[[:digit:]]*')"
  PYTHON_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'python@3.11.9.sh' | grep -o '[[:digit:]]*')"
    PIP_JOB_ID="$(sbatch --dependency="afterok:${PYTHON_JOB_ID}" 'py-pip@24.2.sh' | grep -o '[[:digit:]]*')"
      SETUPTOOLS_JOB_ID="$(sbatch --dependency="afterok:${PIP_JOB_ID}" 'py-setuptools@75.1.0.sh' | grep -o '[[:digit:]]*')"
        NUMPY1_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}:${OPENBLAS_JOB_ID}" 'py-numpy@1.26.4.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-omp.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64-omp.sh' | grep -o '[[:digit:]]*')"
          NUMPY2_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}" 'py-numpy@2.1.2.sh' | grep -o '[[:digit:]]*')"
            ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${NUMPY2_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
            BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY2_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
              ARRAYFIRE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}:${CUDNN_JOB_ID}:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}" 'arrayfire@3.9.0.sh' | grep -o '[[:digit:]]*')"
              CGAL4_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@4.13.sh' | grep -o '[[:digit:]]*')"
              CGAL5_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@5.6.1.sh' | grep -o '[[:digit:]]*')"
              IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-omp.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64-omp.sh' | grep -o '[[:digit:]]*')"
        VENV_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}" 'py-virtualenv@20.26.5.sh' | grep -o '[[:digit:]]*')"
  SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  STREAM_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'stream@5.10.sh' | grep -o '[[:digit:]]*')"
    STREAM_OMP_JOB_ID="$(sbatch --dependency="afterok:${STREAM_JOB_ID}" 'stream@5.10-omp.sh' | grep -o '[[:digit:]]*')"
  UCX_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'ucx@1.14.1.sh' | grep -o '[[:digit:]]*')"
    OPENMPI_JOB_ID="$(sbatch --dependency="afterok:${UCX_JOB_ID}" 'openmpi@4.1.8.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@11.5.0/mvapich2@2.3.7-2"
BOOST_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  NAMD2_JOB_ID="$(sbatch --dependency="afterok:${CHARMPP_JOB_ID}:${FFTW_JOB_ID}" 'namd@2.14.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_OMP_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_OMP_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY2_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${NETLIB_SCALAPACK_JOB_ID}:${PYTHON_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
#    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
#        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${MVAPICH2_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
PLUMED_JOB_ID="$(sbatch --dependency="afterok:${ARRAYFIRE_JOB_ID}:${MVAPICH2_JOB_ID}" 'plumed@2.9.3.sh' | grep -o '[[:digit:]]*')"
  GROMACS_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}:${MVAPICH2_JOB_ID}:${PLUMED_JOB_ID}" 'gromacs@2024.3.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@11.5.0/openmpi@4.1.8"
BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}:${OPENMPI_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  NAMD2_JOB_ID="$(sbatch --dependency="afterok:${CHARMPP_JOB_ID}:${FFTW_JOB_ID}" 'namd@2.14.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_OMP_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_OMP_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY2_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${NETLIB_SCALAPACK_JOB_ID}:${PYTHON_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
#        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${OPENMPI_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
PLUMED_JOB_ID="$(sbatch --dependency="afterok:${ARRAYFIRE_JOB_ID}:${OPENMPI_JOB_ID}" 'plumed@2.9.3.sh' | grep -o '[[:digit:]]*')"
  GROMACS_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}:${PLUMED_JOB_ID}" 'gromacs@2024.3.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@13.3.0"
CUDA_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'cuda@12.6.3.sh' | grep -o '[[:digit:]]*')"
  CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  CUDNN_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cudnn@9.6.0.74-12.sh' | grep -o '[[:digit:]]*')"
  CUTENSOR_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cutensor@2.0.2.5.sh' | grep -o '[[:digit:]]*')"
  NCCL_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'nccl@2.23.4-1.sh' | grep -o '[[:digit:]]*')"
EIGEN_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'eigen@3.4.0.sh' | grep -o '[[:digit:]]*')"
  FFTW_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
    FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
    NAMD2_JOB_ID="$(sbatch --dependency="afterok:${CHARMPP_JOB_ID}:${FFTW_JOB_ID}" 'namd@2.14.sh' | grep -o '[[:digit:]]*')"
  GSL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'gsl@2.8.sh' | grep -o '[[:digit:]]*')"
  LIBXC_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libxc@7.0.0.sh' | grep -o '[[:digit:]]*')"
  LIBBEAGLE_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libbeagle@3.1.2.sh' | grep -o '[[:digit:]]*')"
    BEAST2_JOB_ID="$(sbatch --dependency="afterok:${LIBBEAGLE_JOB_ID}" 'beast2@2.7.7.sh' | grep -o '[[:digit:]]*')"
  HDF5_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
    NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
      NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
      NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
  METIS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'metis@5.1.0.sh' | grep -o '[[:digit:]]*')"
  MVAPICH2_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'mvapich2@2.3.7-2.sh' | grep -o '[[:digit:]]*')"
  NETLIB_LAPACK_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'netlib-lapack@3.12.0.sh' | grep -o '[[:digit:]]*')"
  OPENBLAS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'openblas@0.3.28.sh' | grep -o '[[:digit:]]*')"
    MAGMA_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${OPENBLAS_JOB_ID}" 'magma@2.9.0.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-omp.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64-omp.sh' | grep -o '[[:digit:]]*')"
  PYTHON_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'python@3.11.9.sh' | grep -o '[[:digit:]]*')"
    PIP_JOB_ID="$(sbatch --dependency="afterok:${PYTHON_JOB_ID}" 'py-pip@24.2.sh' | grep -o '[[:digit:]]*')"
      SETUPTOOLS_JOB_ID="$(sbatch --dependency="afterok:${PIP_JOB_ID}" 'py-setuptools@75.1.0.sh' | grep -o '[[:digit:]]*')"
        NUMPY1_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}:${OPENBLAS_JOB_ID}" 'py-numpy@1.26.4.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-omp.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64-omp.sh' | grep -o '[[:digit:]]*')"
          NUMPY2_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}" 'py-numpy@2.1.2.sh' | grep -o '[[:digit:]]*')"
            ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${NUMPY2_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
            BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY2_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
              ARRAYFIRE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}:${CUDNN_JOB_ID}:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}" 'arrayfire@3.9.0.sh' | grep -o '[[:digit:]]*')"
              CGAL4_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@4.13.sh' | grep -o '[[:digit:]]*')"
              CGAL5_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@5.6.1.sh' | grep -o '[[:digit:]]*')"
              IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-omp.sh' | grep -o '[[:digit:]]*')"
            NUMPY2_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64-omp.sh' | grep -o '[[:digit:]]*')"
        VENV_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}" 'py-virtualenv@20.26.5.sh' | grep -o '[[:digit:]]*')"
  SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  STREAM_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'stream@5.10.sh' | grep -o '[[:digit:]]*')"
    STREAM_OMP_JOB_ID="$(sbatch --dependency="afterok:${STREAM_JOB_ID}" 'stream@5.10-omp.sh' | grep -o '[[:digit:]]*')"
  UCX_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'ucx@1.14.1.sh' | grep -o '[[:digit:]]*')"
    OPENMPI_JOB_ID="$(sbatch --dependency="afterok:${UCX_JOB_ID}" 'openmpi@4.1.8.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@13.3.0/mvapich2@2.3.7-2"
BOOST_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_OMP_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_OMP_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY2_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${NETLIB_SCALAPACK_JOB_ID}:${PYTHON_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${MVAPICH2_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
PLUMED_JOB_ID="$(sbatch --dependency="afterok:${ARRAYFIRE_JOB_ID}:${MVAPICH2_JOB_ID}" 'plumed@2.9.3.sh' | grep -o '[[:digit:]]*')"
  GROMACS_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}:${MVAPICH2_JOB_ID}:${PLUMED_JOB_ID}" 'gromacs@2024.3.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/gcc@13.3.0/openmpi@4.1.8"
BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}:${OPENMPI_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_OMP_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${HPL_JOB_ID}:${OPENBLAS_I64_OMP_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY2_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${NETLIB_SCALAPACK_JOB_ID}:${PYTHON_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${OPENMPI_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
PLUMED_JOB_ID="$(sbatch --dependency="afterok:${ARRAYFIRE_JOB_ID}:${OPENMPI_JOB_ID}" 'plumed@2.9.3.sh' | grep -o '[[:digit:]]*')"
  GROMACS_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}:${PLUMED_JOB_ID}" 'gromacs@2024.3.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/intel@2021.10.0"
CUDA_JOB_ID="$(sbatch --dependency="afterok:${GCC_JOB_ID}" 'cuda@12.6.3.sh' | grep -o '[[:digit:]]*')"
#  CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  CUDNN_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cudnn@9.6.0.74-12.sh' | grep -o '[[:digit:]]*')"
  CUTENSOR_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cutensor@2.0.2.5.sh' | grep -o '[[:digit:]]*')"
#  NCCL_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'nccl@2.23.4-1.sh' | grep -o '[[:digit:]]*')"
EIGEN_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_JOB_ID}" 'eigen@3.4.0.sh' | grep -o '[[:digit:]]*')"
  FFTW_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
    FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
  GSL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'gsl@2.8.sh' | grep -o '[[:digit:]]*')"
  LIBXC_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libxc@7.0.0.sh' | grep -o '[[:digit:]]*')"
  LIBBEAGLE_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'libbeagle@3.1.2.sh' | grep -o '[[:digit:]]*')"
    BEAST2_JOB_ID="$(sbatch --dependency="afterok:${LIBBEAGLE_JOB_ID}" 'beast2@2.7.7.sh' | grep -o '[[:digit:]]*')"
  HDF5_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
    NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
      NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
      NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
  INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
    INTEL_ONEAPI_MKL_I64_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'intel-oneapi-mkl@2023.2.0-i64.sh' | grep -o '[[:digit:]]*')"
    INTEL_ONEAPI_MKL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'intel-oneapi-mkl@2023.2.0-omp.sh' | grep -o '[[:digit:]]*')"
    INTEL_ONEAPI_MKL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'intel-oneapi-mkl@2023.2.0-i64-omp.sh' | grep -o '[[:digit:]]*')"
  INTEL_ONEAPI_MPI_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'intel-oneapi-mpi@2021.10.0.sh' | grep -o '[[:digit:]]*')"
  METIS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'metis@5.1.0.sh' | grep -o '[[:digit:]]*')"
  MVAPICH2_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'mvapich2@2.3.7-2.sh' | grep -o '[[:digit:]]*')"
  NETLIB_LAPACK_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'netlib-lapack@3.12.0.sh' | grep -o '[[:digit:]]*')"
  OPENBLAS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'openblas@0.3.28.sh' | grep -o '[[:digit:]]*')"
#    MAGMA_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${OPENBLAS_JOB_ID}" 'magma@2.9.0.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-omp.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64-omp.sh' | grep -o '[[:digit:]]*')"
  PYTHON_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'python@3.11.9.sh' | grep -o '[[:digit:]]*')"
    PIP_JOB_ID="$(sbatch --dependency="afterok:${PYTHON_JOB_ID}" 'py-pip@24.2.sh' | grep -o '[[:digit:]]*')"
      SETUPTOOLS_JOB_ID="$(sbatch --dependency="afterok:${PIP_JOB_ID}" 'py-setuptools@75.1.0.sh' | grep -o '[[:digit:]]*')"
        NUMPY1_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${SETUPTOOLS_JOB_ID}" 'py-numpy@1.26.4.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-omp.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64-omp.sh' | grep -o '[[:digit:]]*')"
            ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
#            BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#              ARRAYFIRE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}" 'arrayfire@3.9.0.sh' | grep -o '[[:digit:]]*')"
#              CGAL4_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@4.13.sh' | grep -o '[[:digit:]]*')"
#              CGAL5_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@5.6.1.sh' | grep -o '[[:digit:]]*')"
#              IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
        VENV_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}" 'py-virtualenv@20.26.5.sh' | grep -o '[[:digit:]]*')"
  SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  STREAM_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'stream@5.10.sh' | grep -o '[[:digit:]]*')"
    STREAM_OMP_JOB_ID="$(sbatch --dependency="afterok:${STREAM_JOB_ID}" 'stream@5.10-omp.sh' | grep -o '[[:digit:]]*')"
  UCX_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}:${EIGEN_JOB_ID}" 'ucx@1.14.1.sh' | grep -o '[[:digit:]]*')"
    OPENMPI_JOB_ID="$(sbatch --dependency="afterok:${UCX_JOB_ID}" 'openmpi@4.1.8.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/intel@2021.10.0/intel-oneapi-mpi@2021.10.0"
#BOOST_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${INTEL_ONEAPI_MPI_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${OPENBLAS_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
#        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${METIS_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
#  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/intel@2021.10.0/mvapich2@2.3.7-2"
#BOOST_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${MVAPICH2_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
#    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
#        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${MVAPICH2_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
#  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/intel@2021.10.0/openmpi@4.1.8"
#BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}:${OPENMPI_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${OPENMPI_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_I64_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
#    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
KAHIP_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}:${OPENMPI_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
#        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${METIS_JOB_ID}:${OPENMPI_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${OPENMPI_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
#  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"

cd "${SLURM_SUBMIT_DIR}/specs/oneapi@2023.2.4"
CUDA_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_JOB_ID}" 'cuda@12.6.3.sh' | grep -o '[[:digit:]]*')"
  #CHARMPP_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'charmpp@6.10.2.sh' | grep -o '[[:digit:]]*')"
  CUDNN_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cudnn@9.6.0.74-12.sh' | grep -o '[[:digit:]]*')"
  CUTENSOR_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'cutensor@2.0.2.5.sh' | grep -o '[[:digit:]]*')"
  #NCCL_JOB_ID="$(sbatch --dependency="afterok:${CUDA_JOB_ID}" 'nccl@2.23.4-1.sh' | grep -o '[[:digit:]]*')"
EIGEN_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_JOB_ID}" 'eigen@3.4.0.sh' | grep -o '[[:digit:]]*')"
#    NAMD2_JOB_ID="$(sbatch --dependency="afterok:${CHARMPP_JOB_ID}:${AMDFFTW_JOB_ID}" 'namd@2.14.sh' | grep -o '[[:digit:]]*')"
  FFTW_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
    FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
  GSL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'gsl@2.8.sh' | grep -o '[[:digit:]]*')"
#  LIBXC_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'libxc@7.0.0.sh' | grep -o '[[:digit:]]*')"
#  LIBBEAGLE_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'libbeagle@3.1.2.sh' | grep -o '[[:digit:]]*')"
#    BEAST2_JOB_ID="$(sbatch --dependency="afterok:${LIBBEAGLE_JOB_ID}" 'beast2@2.7.7.sh' | grep -o '[[:digit:]]*')"
  HDF5_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
#    NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
#      NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
#      NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
  INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
    INTEL_ONEAPI_MKL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'intel-oneapi-mkl@2023.2.0-omp.sh' | grep -o '[[:digit:]]*')"
  INTEL_ONEAPI_MPI_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'intel-oneapi-mpi@2021.10.0.sh' | grep -o '[[:digit:]]*')"
  METIS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'metis@5.1.0.sh' | grep -o '[[:digit:]]*')"
#  MVAPICH2_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'mvapich2@2.3.7-2.sh' | grep -o '[[:digit:]]*')"
  NETLIB_LAPACK_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'netlib-lapack@3.12.0.sh' | grep -o '[[:digit:]]*')"
  OPENBLAS_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'openblas@0.3.28.sh' | grep -o '[[:digit:]]*')"
    MAGMA_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'magma@2.9.0.sh' | grep -o '[[:digit:]]*')"
#    OPENBLAS_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64.sh' | grep -o '[[:digit:]]*')"
    OPENBLAS_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-omp.sh' | grep -o '[[:digit:]]*')"
#    OPENBLAS_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_JOB_ID}" 'openblas@0.3.28-i64-omp.sh' | grep -o '[[:digit:]]*')"
  PYTHON_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'python@3.11.9.sh' | grep -o '[[:digit:]]*')"
    PIP_JOB_ID="$(sbatch --dependency="afterok:${PYTHON_JOB_ID}" 'py-pip@24.2.sh' | grep -o '[[:digit:]]*')"
      SETUPTOOLS_JOB_ID="$(sbatch --dependency="afterok:${PIP_JOB_ID}" 'py-setuptools@75.1.0.sh' | grep -o '[[:digit:]]*')"
        NUMPY1_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${SETUPTOOLS_JOB_ID}" 'py-numpy@1.26.4.sh' | grep -o '[[:digit:]]*')"
#          NUMPY1_I64_JOB_ID="$(sbatch --dependency="afterok:${AMDLIBFLAME_I64_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64.sh' | grep -o '[[:digit:]]*')"
          NUMPY1_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-omp.sh' | grep -o '[[:digit:]]*')"
#          NUMPY1_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${AMDLIBFLAME_I64_OMP_JOB_ID}:${NUMPY1_JOB_ID}" 'py-numpy@1.26.4-i64-omp.sh' | grep -o '[[:digit:]]*')"
#          NUMPY2_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}" 'py-numpy@2.1.2.sh' | grep -o '[[:digit:]]*')"
            ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
#            BOOST_JOB_ID="$(sbatch --dependency="afterok:${NUMPY2_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#              ARRAYFIRE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}:${FFTW_JOB_ID}:${OPENBLAS_JOB_ID}" 'arrayfire@3.9.0.sh' | grep -o '[[:digit:]]*')"
#              CGAL4_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@4.13.sh' | grep -o '[[:digit:]]*')"
#              CGAL5_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'cgal@5.6.1.sh' | grep -o '[[:digit:]]*')"
#              IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
#            NUMPY2_I64_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64.sh' | grep -o '[[:digit:]]*')"
#            NUMPY2_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-omp.sh' | grep -o '[[:digit:]]*')"
#            NUMPY2_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${OPENBLAS_I64_OMP_JOB_ID}:${NUMPY2_JOB_ID}" 'py-numpy@2.1.2-i64-omp.sh' | grep -o '[[:digit:]]*')"
#        VENV_JOB_ID="$(sbatch --dependency="afterok:${SETUPTOOLS_JOB_ID}" 'py-virtualenv@20.26.5.sh' | grep -o '[[:digit:]]*')"
#  SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
  STREAM_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'stream@5.10.sh' | grep -o '[[:digit:]]*')"
    STREAM_OMP_JOB_ID="$(sbatch --dependency="afterok:${STREAM_JOB_ID}" 'stream@5.10-omp.sh' | grep -o '[[:digit:]]*')"
#  UCX_JOB_ID="$(sbatch --dependency="afterok:${EIGEN_JOB_ID}" 'ucx@1.14.1.sh' | grep -o '[[:digit:]]*')"
#    OPENMPI_JOB_ID="$(sbatch --dependency="afterok:${UCX_JOB_ID}" 'openmpi@4.1.8.sh' | grep -o '[[:digit:]]*')"
#
cd "${SLURM_SUBMIT_DIR}/specs/oneapi@2023.2.4/intel-oneapi-mpi@2021.10.0"
#BOOST_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${NUMPY1_JOB_ID}" 'boost@1.86.0.sh' | grep -o '[[:digit:]]*')"
#  IQTREE_JOB_ID="$(sbatch --dependency="afterok:${BOOST_JOB_ID}" 'iq-tree@2.3.6.sh' | grep -o '[[:digit:]]*')"
FFTW_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'fftw@3.3.10.sh' | grep -o '[[:digit:]]*')"
  FFTW_OMP_JOB_ID="$(sbatch --dependency="afterok:${FFTW_JOB_ID}" 'fftw@3.3.10-omp.sh' | grep -o '[[:digit:]]*')"
HDF5_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'hdf5@1.14.3.sh' | grep -o '[[:digit:]]*')"
#  QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
HPL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}:${INTEL_ONEAPI_MPI_JOB_ID}" 'hpl@2.3.sh' | grep -o '[[:digit:]]*')"
#  HPL_I64_JOB_ID="$(sbatch --dependency="afterok:${AMDBLIS_I64_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64.sh' | grep -o '[[:digit:]]*')"
  HPL_OMP_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-omp.sh' | grep -o '[[:digit:]]*')"
#  HPL_I64_OMP_JOB_ID="$(sbatch --dependency="afterok:${AMDBLIS_I64_OMP_JOB_ID}:${HPL_JOB_ID}" 'hpl@2.3-i64-omp.sh' | grep -o '[[:digit:]]*')"
INTEL_ONEAPI_MKL_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'intel-oneapi-mkl@2023.2.0.sh' | grep -o '[[:digit:]]*')"
  ELPA_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MKL_JOB_ID}" 'elpa@2024.03.001.sh' | grep -o '[[:digit:]]*')"
#    QUANTUM_ESPRESSO_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${ELPA_JOB_ID}" 'quantum-espresso@7.4.1.sh' | grep -o '[[:digit:]]*')"
#KAHIP_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'kahip@3.16.sh' | grep -o '[[:digit:]]*')"
MPI4PY_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${PYTHON_JOB_ID}" 'py-mpi4py@4.0.0.sh' | grep -o '[[:digit:]]*')"
  ADIOS2_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${MPI4PY_JOB_ID}:${NUMPY1_JOB_ID}" 'adios2@2.10.1.sh' | grep -o '[[:digit:]]*')"
#  NEURON_JOB_ID="$(sbatch --dependency="afterok:${MPI4PY_JOB_ID}:${NUMPY2_JOB_ID}" 'neuron@8.2.3.sh' | grep -o '[[:digit:]]*')"
#NETLIB_SCALAPACK_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}:${OPENBLAS_JOB_ID}" 'netlib-scalapack@2.2.0.sh' | grep -o '[[:digit:]]*')"
OMB_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'osu-micro-benchmarks@7.4.sh' | grep -o '[[:digit:]]*')"
#PARALLEL_NETCDF_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'parallel-netcdf@1.13.0.sh' | grep -o '[[:digit:]]*')"
#  IOR_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'ior@3.3.0.sh' | grep -o '[[:digit:]]*')"
#  NETCDF_C_JOB_ID="$(sbatch --dependency="afterok:${HDF5_JOB_ID}:${PARALLEL_NETCDF_JOB_ID}" 'netcdf-c@4.9.2.sh' | grep -o '[[:digit:]]*')"
#    NETCDF_CXX4_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-cxx4@4.3.1.sh' | grep -o '[[:digit:]]*')"
#    NETCDF_FORTRAN_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_C_JOB_ID}" 'netcdf-fortran@4.6.1.sh' | grep -o '[[:digit:]]*')"
#      WRF_JOB_ID="$(sbatch --dependency="afterok:${NETCDF_FORTRAN_JOB_ID}" 'wrf@4.6.0.sh' | grep -o '[[:digit:]]*')"
##        WPS_JOB_ID="$(sbatch --dependency="afterok:${WRF_JOB_ID}" 'wps@4.6.0.sh' | grep -o '[[:digit:]]*')"
PARMETIS_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}:${METIS_JOB_ID}" 'parmetis@4.0.3.sh' | grep -o '[[:digit:]]*')"
#  ZOLTAN_JOB_ID="$(sbatch --dependency="afterok:${PARMETIS_JOB_ID}" 'zoltan@3.901.sh' | grep -o '[[:digit:]]*')"
RAXML_JOB_ID="$(sbatch --dependency="afterok:${INTEL_ONEAPI_MPI_JOB_ID}" 'raxml@8.2.13.sh' | grep -o '[[:digit:]]*')"
#RAXML_NG_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'raxml-ng@1.2.2.sh' | grep -o '[[:digit:]]*')"
#SCOTCH_JOB_ID="$(sbatch --dependency="afterok:${MVAPICH2_JOB_ID}" 'scotch@7.0.5.sh' | grep -o '[[:digit:]]*')"
#  OPENFOAM_JOB_ID="$(sbatch --dependency="afterok:${ADIOS2_JOB_ID}:${CGAL5_JOB_ID}:${SCOTCH_JOB_ID}:${ZOLTAN_JOB_ID}" 'openfoam@2406.sh' | grep -o '[[:digit:]]*')"
